# Generated by Django 3.2.9 on 2021-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('text', models.TextField(max_length=300, verbose_name='текст')),
                ('link', models.URLField(verbose_name='ссылка на источник')),
                ('short_link', models.CharField(max_length=100, verbose_name='краткая ссылка')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'совет',
                'verbose_name_plural': 'Советы',
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=10, verbose_name='версия приложения')),
            ],
            options={
                'verbose_name': 'версия приложения',
                'verbose_name_plural': 'Версия приложения',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('text', models.TextField(max_length=300, verbose_name='текст')),
                ('link', models.URLField(verbose_name='ссылка на источник')),
                ('short_link', models.CharField(max_length=100, verbose_name='краткая ссылка')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'о пользе воды',
                'verbose_name_plural': 'О пользе воды',
            },
        ),
        migrations.CreateModel(
            name='LegalDocs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('policy', models.TextField(max_length=30000, verbose_name='политика конфиденциальности')),
                ('terms', models.TextField(max_length=30000, verbose_name='условия использования')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'правовой документ',
                'verbose_name_plural': 'Правовые документы',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='будут видны как варианты при отправке негативного отзыва', max_length=30, verbose_name='вопрос')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='название')),
                ('cost', models.IntegerField(verbose_name='стоимость')),
                ('price_per_month', models.IntegerField(default=0, verbose_name='цена за месяц')),
                ('month', models.IntegerField(default=0, verbose_name='количество месяцев')),
                ('unlimited', models.BooleanField(default=False, verbose_name='безлимитный')),
                ('discount', models.IntegerField(default=0, verbose_name='процент скидки')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
